<?php

namespace SM\LoginBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FonctionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionsRepository extends EntityRepository
{
}
